from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^clear/$', views.clear),
    url(r'^status/$', views.status),
    url(r'^forum/create/$', views.createforum),
    url(r'^forum/details/$', views.detailsforum),
    url(r'^forum/listPosts/$', views.listpostsforum),
    url(r'^forum/listThreads/$', views.listthreadsforum),
    url(r'^forum/listUsers/$', views.listusersforum),
    url(r'^post/create/$', views.createpost ),
    url(r'^post/details/$', views.detailspost ),
    url(r'^post/list/$', views.listpost ),
    url(r'^post/remove/$', views.removepost ),
    url(r'^post/restore/$', views.restorepost),
    url(r'^post/update/$', views.updatepost ),
    url(r'^post/vote/$', views.votepost),
    url(r'^user/create/$', views.createuser),
    url(r'^user/details/$', views.detailsuser),
    url(r'^user/follow/$', views.followuser),
    url(r'^user/listFollowers/$', views.listfollowersuser),
    url(r'^user/listFollowing/$', views.listfollowinguser),
    url(r'^user/listPosts/$', views.listpostsuser),
    url(r'^user/unfollow/$', views.unfollowuser),
    url(r'^user/updateProfile/$', views.updateprofileuser),
    url(r'^thread/close/$', views.closethread),
    url(r'^thread/create/$', views.createthread),
    url(r'^thread/details/$', views.detailsthread),
    url(r'^thread/list/$', views.listthread),
    url(r'^thread/listPosts/$', views.listpoststhread),
    url(r'^thread/open/$', views.openthread),
    url(r'^thread/remove/$', views.removethread),
    url(r'^thread/restore/$', views.restorethread),
    url(r'^thread/subscribe/', views.subscribethread),
    url(r'^thread/unsubscribe/$', views.unsubscribethread),
    url(r'^thread/update/$', views.updatethread),
    url(r'^thread/vote/$', views.votethread),
    url(r'^user/create/$', views.createuser),
    url(r'^user/details/$', views.detailsuser),
    url(r'^user/follow/$', views.followuser),
    url(r'^user/listFollowers/$', views.listfollowersuser),
]

